- name: Deploy Code on App Servers
  hosts: awsdevubapp*
  gather_facts: false
  tasks:
    - name: Copy Py file from local to app server
      become: yes
      copy:
        src: mySqlDB.py
        dest: /usr/lib/cgi-bin/mySqlDB.py
        mode: '0755'
