- name: Provision WEB server
  hosts: awsdevrhweb*
  tasks:
  - name: Install apache packages
    become: yes
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    become: yes
    service:
      name: httpd
      state: started
